### PR TITLE
Replacement of RHEL9-DES for AES

### LINKED ISSUE #16: RHEL9 requires AES replacemed instead of DES at one point in the Code
RHEL9 Systems will complain about DES Cipher use, 
- and the following will need to be changed in ` snmp_bulkget.c` :

```
/session->securityPrivProto = snmp_duplicate_objid(usmDESPrivProtocol, USM_PRIV_PROTO_DES_LEN);
```
to

```
/session->securityPrivProto = snmp_duplicate_objid(usmAESPrivProtocol, USM_PRIV_PROTO_DES_LEN);
```
- recompilation then is required (for example like this), and everything should work after :
```
gcc -o check_interfaces snmp_bulkget.o utils.o -lrt -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -fPIE -lm -L/usr/lib64 -lnetsnmp -lssl -lcrypto -lm -lnetsnmp
```

### PR DESCRIPTION
**Pull request by pdolinic**
Fixes #16

### CODE REVIEW

**Review by dgoetz — CHANGES_REQUESTED** [review]
`dnf update` should not be included (it is not the same as `apt update`.

Makefile should be adjusted instead of describing how to do a recompile afterwards.

Commit message should tell what is happening (https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/ for example is a guide on how to write good commit messages).

**Comment by martialblog** [comment]
@pdolinic Will you take care of the requested changes? or should someone take over?

**Comment by pdolinic** [comment]
> @pdolinic Will you take care of the requested changes? or should someone take over?

I'll be on holidays till the 10th, if you want you can take over here @martialblog. It's mostly getting the documentation right, the code change is just one of an AES string.

**Comment by RincewindsHat** [comment]
Also, have you tried `-k AES`?

**Pull request closed without merging**
