### PR TITLE
Make -a/-A working as expected

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by Al2Klimov** [comment]
ref/IP/33377

**Comment by Al2Klimov** [comment]
Any news on the western front?

Btw. the customer is happy with this changeset:

https://rt.icinga.com/Ticket/Display.html?id=33377#txn-550077

**Comment by Al2Klimov** [comment]
_PING_ @mxhash

**Review by htriem — APPROVED** [review]
LGTM! 👍

**Pull request merged**
