### PR TITLE
README: add building prerequisites for FreeBSD

### PR DESCRIPTION
**Pull request by mrdsam**

### CODE REVIEW

**Comment by RincewindsHat** [comment]
Thank you so much :-) I don't know much about the FreeBSD infrastructure, so please allow me to ask whether it is necessary to gather the whole source or is there an easier way to get the library for `net-snmp`?

**Comment by mrdsam** [comment]
I took a closer look - yes, /usr/src is *not* needed. The version a few days ago didn't build w/o the src-component, but now, maybe because of 'autoreconf', it builds without it.
```
checking for net-snmp-config... /usr/local/bin/net-snmp-config
```
For this, only the package 'net-snmp' has to be installed

**Comment by RincewindsHat** [comment]
Funny you should mention that, I just tried to reproduce this on a freebsd 13.2 vm I have here and it fails now in the configure script in the step after that :-)

```
configure: error: Net-SNMP library unusable - either it is missing or there are unfulfilled dependencies (e.g. libcrypto)
```

**Comment by RincewindsHat** [comment]
funny, didn't have gcc installed, works then. Maybe `net-snmp` has some GNUisms in it and doesn't like `cc`?

**Comment by mrdsam** [comment]
Sorry, I have no idea. But this happens with a lot of software I try to compile.

**Pull request closed without merging**
